//extra whitespace being added to string generated by QR code, added code to trim whitespace
import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, Alert } from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { auth, db } from '../firebase';
import { doc, getDoc, updateDoc, arrayUnion } from 'firebase/firestore';

export default function QRScannerScreen({ navigation }) {
    const [permission, requestPermission] = useCameraPermissions();
    const [scanned, setScanned] = useState(false);

    useEffect(() => {
        if (!permission?.granted) requestPermission();
    }, []);

    const handleBarCodeScanned = async ({ data }) => {
        if (scanned) return;
        setScanned(true);
        //console.log('Scanned data:', data);

        const prefix = 'dustbuddies:item:';
        if (!data.startsWith(prefix)) {
            Alert.alert('Invalid QR Code', 'This code is not a DustBuddies item.', [
                { text: 'Try Again', onPress: () => setScanned(false) },
            ]);
            return;
        }

        const itemKey = data.replace(prefix, '').trim();
        const uid = auth.currentUser?.uid;
        if (!uid) return;

        const userRef = doc(db, 'users', uid);
        //console.log('Fethcing doc for uid:', uid);
        const userSnap = await getDoc(userRef);
        //console.log('Got snap:', userSnap.exists());
        const unlockedItems = userSnap.data()?.unlockedItems ?? [];

        if (unlockedItems.includes(itemKey)) {
            Alert.alert("Already Unlocked", "You already have this item!", [
                { text: 'OK', onPress: () => navigation.goBack() },
            ]);
            return;
        }
        try {
            await updateDoc(userRef, { unlockedItems: arrayUnion(itemKey) });
            Alert.alert('Item Unlocked!', `You unlocked: ${itemKey}`, [
                { text: 'OK', onPress: () => navigation.goBack() },
            ]);
        } catch (error) {
            //console.log('Firestore error:', error);
            //Alert.alert('Error', error.message);
        }
    };

    if (!permission?.granted) {
        return (
            <View style={styles.center}>
                <Text>Camera permission is required to scan QR codes.</Text>
            </View>
        );
    }

    return (
        <CameraView
            style={StyleSheet.absoluteFillObject}
            onBarcodeScanned={handleBarCodeScanned}
            barcodeScannerSettings={{ barcodeTypes: ['qr'] }}
        />
    );
}

const styles = StyleSheet.create({
    center: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center'
    },
});